---
- name: Check vars
  ansible.builtin.include_tasks: check_vars.yml

- name: Download Redis tarball
  when: redis_install_from_source
  ansible.builtin.include_tasks: download.yml
  tags:
    - download

- name: Install dependencies
  when: redis_install_from_source
  ansible.builtin.include_tasks: dependencies.yml
  tags:
    - install

- name: Install redis from source
  when: redis_install_from_source
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: Install redis from repo
  when: not redis_install_from_source
  ansible.builtin.include_tasks: install_from_repo.yml
  tags:
    - install

- name: Install and configure redis server
  when: redis_server
  ansible.builtin.include_tasks: server.yml
  tags:
    - config

- name: Install and configure redis sentinel
  when: redis_sentinel
  ansible.builtin.include_tasks: sentinel.yml
  tags:
    - config

- name: Get redis facts
  when: redis_local_facts|bool
  ansible.builtin.include_tasks: local_facts.yml
